### ISSUE TITLE
Srt not produce

### ISSUE THREAD

**Issue by afdhalrashid** [bleggett/subtitle-overlap-fixer#2]
I have try the code to resync youtube subs, but the output result is .fixed file with 0 kb size

**Comment by afdhalrashid** [comment]
![test srt](https://user-images.githubusercontent.com/26217286/81425938-1068b280-918b-11ea-98bd-8e1b2a0f5fc5.gif)

*remove .gif, actual extension is .srt

**Comment by thibaud** [comment]
Interesting script, however it erases all the timestamps compacting all the text and keeping only one timestamp...

**Comment by bleggett** [comment]
@thibaud 

Note the README:

`Combines subtitles if the end-time of the previous subtitle overlaps with the start-time of the current subtitle.`

This is a hack/workaround to fix a problem with `ffmpeg`'s VTT to SRT conversion, which is incorrect.

The hack/workaround is to collapse subtitles with overlapping timecodes specifically.

If you don't understand the `ffmpeg` VTT to SRT conversion bug this is trying to fix after-the-fact, it won't be much use to you. It is not a subtitle conversion utility, it does not resync out of sync subs - `ffmpeg` does that. 

This simply corrects invalid/non-compliant outputs from `ffmpeg`.
